### ISSUE TITLE
Bump package version so fix in #3 is available via npm

### ISSUE THREAD

**Issue by ooloth** [florianeckerstorfer/gatsby-remark-a11y-emoji#4]
Hi there!

Love this plugin, but I'm still getting console errors caused by the "aria-labelled-by" attribute appearing on the `span` instead of the correct "aria-label".

I believe this was fixed by #3, so can you please release a new version so we can download the improved code via npm?

**Comment by florianeckerstorfer** [comment]
Oh yes, thanks. v1.0.1 is released
