### ISSUE TITLE
Support for MDX files

### ISSUE THREAD

**Issue by iloveip** [florianeckerstorfer/gatsby-remark-a11y-emoji#51]
HI there,
Does this plugin work with `MDX` files? 

UPDATE:
I've installed the plugin and added it to my `gatsby-config.js` as follow:
```
const emoji = require(`gatsby-remark-a11y-emoji`);

{
  resolve: `gatsby-plugin-mdx`,
  options: {
    remarkPlugins: [emoji]
  }
}
```

But I get the following error:
```
TypeError: Cannot destructure property 'markdownAST' of 'undefined' as it is undefined.
- index.js:18 Function.module.exports
    [my-gatsby]/[gatsby-remark-a11y-emoji]/index.js:18:3
```

**Comment by florianeckerstorfer** [comment]
@iloveip I think this is because how Gatsby invokes Remark Plugins, their implementation is a bit custom. However, I have another package that is a "standard" Remark plugin: https://github.com/florianeckerstorfer/remark-a11y-emoji

**Comment by iloveip** [comment]
Thank you very much! It works great!
