### ISSUE TITLE
Tag <undefined> appears near emojis

### ISSUE THREAD

**Issue by UgRoss** [florianeckerstorfer/gatsby-remark-a11y-emoji#67]
Hello 👋!

**Describe the bug**
It looks like emojis are not processed correctly when they are used inside the titles.

**To Reproduce**
1. Create some MDX document 
2. Use titles with emojis. For example, `### ⚒️ Tools`
3. Check rendered result

**Expected behavior**
There should not be any `<undefined />` tags near the title

**Screenshots**

Here is what I get when I try to parse some MDX document:

![CleanShot 2021-03-05 at 11 07 43@2x](https://user-images.githubusercontent.com/5703885/110093207-1deacb00-7da3-11eb-99cb-9ed61c18ed42.png)

config:

```javascript
{
      resolve: `gatsby-plugin-mdx`,
      options: {
        extensions: [`.md`, `.mdx`],
        gatsbyRemarkPlugins: [
          //....
          'gatsby-remark-a11y-emoji',
        ]
      }
}
```

Here is how it looks if I just use `remark-a11y-emoji`:

![CleanShot 2021-03-05 at 11 13 35@2x](https://user-images.githubusercontent.com/5703885/110093891-e3cdf900-7da3-11eb-89a0-5283e41d0492.png)

Config:

```javascript
{
      resolve: `gatsby-plugin-mdx`,
      options: {
        extensions: [`.md`, `.mdx`],
        gatsbyRemarkPlugins: [
          //....
        ],
        remarkPlugins: [require('@fec/remark-a11y-emoji')],
     }
}
```

**Environment (please complete the following information):**
 - OS: Mac OS
 - Node Version: v14.15.1 
 - Gatsby Version: ^2.32.8
 - gatsby-plugin-mdx: ^1.10.1
 - Version: ^1.1.0

**Additional context**
In case you can't represent it, here is the whole MDX config inside the `gatsby-config`:

```javascript
   {
      resolve: `gatsby-plugin-mdx`,
      options: {
        extensions: [`.md`, `.mdx`],
        gatsbyRemarkPlugins: [
          { resolve: `gatsby-remark-relative-images` },
          { resolve: 'gatsby-remark-images', options: { maxWidth: 750 } },
          { resolve: 'gatsby-remark-responsive-iframe' },
          `gatsby-remark-prismjs`,
          'gatsby-remark-copy-linked-files',
          'gatsby-remark-a11y-emoji',
          { resolve: 'gatsby-remark-external-links', options: { target: '_blank' } },
        ]
      },
    }
```

**Comment by florianeckerstorfer** [comment]
@UgRoss Thanks for the very detailed bug description. Good news is that `@fec/remark-a11y-emoji` works correctly and I'm currently planning to deprecate this package and put the gatsby-remark plugin as a thin wrapper into the `@fec/remark-a11y-emoji` package. I will try to get a version published this weekend and update you here.

**Comment by UgRoss** [comment]
Got it! Thanks for the explanation! 👍

**Comment by florianeckerstorfer** [comment]
@UgRoss  @fec/remark-a11y-emoji v3.1.0 has been released, which now includes a Gatsby plugin.

**Comment by UgRoss** [comment]
@florianeckerstorfer thank you!
